package toolchain

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"runtime"
	"sort"
	"strings"
	"sync"

	"github.com/Sawmonabo/codectx/internal/model"
)

// lockJSON is the pinned tool table the shipped binary carries. It is the
// product's trust root: a payload is runnable because it hashes to what this
// file records. It is generated by internal/tools/toollock at release time and
// is never edited by hand.
//
//go:embed tools.lock.json
var lockJSON []byte

// Platform is one supported target of Section 24.
type Platform struct{ OS, Arch string }

// Current is the platform this binary is running on.
func Current() Platform { return Platform{OS: runtime.GOOS, Arch: runtime.GOARCH} }

// Key is the lock's spelling of a platform, "<os>_<arch>". It is a method
// rather than a format string repeated at each call site because the lock
// generator, the resolver and the status report must agree on it exactly.
func (p Platform) Key() string { return p.OS + "_" + p.Arch }

// supportedPlatforms is the Section 24 target list. A lock naming any other
// key is malformed: an unknown key would silently never match and the tool
// would look unavailable everywhere.
var supportedPlatforms = map[string]bool{
	"linux_amd64": true, "linux_arm64": true,
	"darwin_amd64": true, "darwin_arm64": true,
	"windows_amd64": true, "windows_arm64": true,
}

// lockKinds are the Section 11.7 tool kinds.
var lockKinds = map[string]bool{"indexer": true, "server": true, "cpg": true, "runtime": true}

// lockRuntimes are the launchers a tool may need. The empty string is a tool
// that runs as itself.
var lockRuntimes = map[string]bool{"": true, "node": true, "jdk": true}

// maxPayloadBytes bounds a single lock payload. The largest thing the lock
// carries is the dependence engine distribution at a few hundred megabytes;
// four gigabytes is a lock that is wrong. The operative cap on a real fetch is
// tools.max_fetch_bytes, which defaults well below this; the value here only
// stops a malformed lock from ever describing an unbounded download.
const maxPayloadBytes = 4 << 30

// Payload is one platform's artifact for a tool.
//
// Entry and EntrySHA256 repeat the tool-level fields per platform because a
// native launcher is a different file on each one -- bin/node against node.exe,
// six distinct bin/java binaries -- so no single tool-level digest can be true
// for more than one of them. The per-platform value wins whenever it is set;
// the tool-level field is the value that holds on the majority of platforms and
// is what a platform-independent payload (a jar, an npm tree) carries alone.
type Payload struct {
	URL    string `json:"url"`
	SHA256 string `json:"sha256"`
	Size   int64  `json:"size"`
	Entry  string `json:"entry,omitempty"`
	// EntrySHA256 is this platform's entry digest.
	EntrySHA256 string `json:"entry_sha256,omitempty"`
	// Provenance says where the payload at URL comes from under the hybrid
	// hosting rule of Section 11.7: "upstream" is pinned at the publisher's own
	// asset URL, "built" is compiled at release time and hosted on the
	// tools-v<n> release because upstream publishes no binary for that
	// platform. It is a provenance record, not something resolution branches on.
	Provenance string `json:"provenance,omitempty"`
	// UpstreamDigest is the "<algo>:<hex>" the upstream publisher declared for
	// this artifact, where one is published at all. The release generator
	// verifies the downloaded bytes against it before recording them, so it is
	// an audit trail of that generation-time check. Nothing at run time verifies
	// against it -- SHA256 above is the run-time trust root, and it is the
	// digest of exactly the bytes this product accepts.
	UpstreamDigest string `json:"upstream_digest,omitempty"`
}

// Entry is one pinned tool. The JSON spelling is the lock schema and is shared
// with the generator in internal/tools/toollock; changing a tag changes the
// on-disk format.
type Entry struct {
	Name        string             `json:"name"`
	Version     string             `json:"version"`
	Kind        string             `json:"kind"`
	License     string             `json:"license"`
	Upstream    string             `json:"upstream"`
	Runtime     string             `json:"runtime"`
	Entry       string             `json:"entry"`
	EntrySHA256 string             `json:"entry_sha256"`
	Platforms   map[string]Payload `json:"platforms"`
	// Languages is the generator's copy of the Section 11.7 matrix row. It is
	// preferred over the package's own table so the two cannot drift.
	Languages []string `json:"languages,omitempty"`
	// Notes is generator commentary; nothing reads it at run time.
	Notes string `json:"notes,omitempty"`
}

// entryPath is the payload-relative executable, script or jar for one platform.
func (e Entry) entryPath(p Payload) string {
	if p.Entry != "" {
		return p.Entry
	}
	return e.Entry
}

// entryDigest is the pinned SHA-256 of that entry.
func (e Entry) entryDigest(p Payload) string {
	if p.EntrySHA256 != "" {
		return p.EntrySHA256
	}
	return e.EntrySHA256
}

// Lock is the whole pinned table.
type Lock struct {
	LockVersion int              `json:"lock_version"`
	Tools       map[string]Entry `json:"tools"`
}

// lockVersion is the only schema this binary understands. A lock is shipped
// inside the binary that reads it, so a mismatch is a build defect, not
// something a user can encounter or migrate.
const lockVersion = 1

var (
	embeddedOnce sync.Once
	embedded     Lock
)

// Embedded returns the parsed embedded lock. It parses and validates once and
// panics on a malformed lock, because a binary whose trust root will not parse
// cannot run any managed tool and every later error would be a confusing
// symptom of the same build defect.
//
// The returned Lock is a deep copy: Tools and every Platforms map are trust
// data, and a caller must not be able to retarget a URL or a digest another
// caller is about to verify against.
func Embedded() Lock {
	embeddedOnce.Do(func() {
		l, err := ParseLock(lockJSON)
		if err != nil {
			panic("toolchain: embedded tools.lock.json is malformed: " + err.Error())
		}
		embedded = l
	})
	return embedded.clone()
}

// ParseLock decodes and validates one lock document. It is exported so the
// release-time generator in internal/tools/toollock validates what it wrote
// with the same code the runtime trusts, rather than a second implementation
// that can drift from it.
func ParseLock(data []byte) (Lock, error) {
	var l Lock
	dec := json.NewDecoder(strings.NewReader(string(data)))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&l); err != nil {
		return Lock{}, invalid("tool lock is not valid JSON: %v", err)
	}
	if dec.More() {
		return Lock{}, invalid("tool lock carries trailing content after the document")
	}
	if err := validateLock(l); err != nil {
		return Lock{}, err
	}
	return l.clone(), nil
}

// Names lists the lock's tools in name order.
func (l Lock) Names() []string {
	names := make([]string, 0, len(l.Tools))
	for name := range l.Tools {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// clone deep-copies the lock so no holder can mutate another's trust data.
func (l Lock) clone() Lock {
	out := Lock{LockVersion: l.LockVersion, Tools: make(map[string]Entry, len(l.Tools))}
	for name, e := range l.Tools {
		platforms := make(map[string]Payload, len(e.Platforms))
		for key, p := range e.Platforms {
			platforms[key] = p
		}
		e.Platforms = platforms
		out.Tools[name] = e
	}
	return out
}

// validateLock rejects every lock the resolver would otherwise have to
// second-guess at run time: an unknown schema version, a name that disagrees
// with its key, a digest that is not a lowercase SHA-256, a size that is not
// positive and bounded, a runtime that names no entry, or an entry path that is
// not confined to the payload.
func validateLock(l Lock) error {
	if l.LockVersion != lockVersion {
		return invalid("tool lock version is %d, this binary reads version %d", l.LockVersion, lockVersion)
	}
	for _, name := range l.Names() {
		e := l.Tools[name]
		if err := validEntry(l, name, e); err != nil {
			return err
		}
	}
	return nil
}

func validEntry(l Lock, name string, e Entry) error {
	if err := validToolName(name); err != nil {
		return err
	}
	if e.Name != name {
		return invalid("tool lock entry %q records the name %q", name, e.Name)
	}
	if e.Version == "" || len(e.Version) > maxVersionBytes {
		return invalid("tool %q needs an exact version of at most %d bytes", name, maxVersionBytes)
	}
	if !lockKinds[e.Kind] {
		return invalid("tool %q has kind %q, which is not indexer, server, cpg or runtime", name, e.Kind)
	}
	if e.License == "" {
		return invalid("tool %q records no license; every redistributed payload has one", name)
	}
	if e.Upstream == "" {
		return invalid("tool %q records no upstream distribution", name)
	}
	if !lockRuntimes[e.Runtime] {
		return invalid("tool %q names runtime %q, which is not node or jdk", name, e.Runtime)
	}
	if e.Runtime != "" {
		rt, ok := l.Tools[e.Runtime]
		switch {
		case !ok:
			return invalid("tool %q needs runtime %q, which the lock does not carry", name, e.Runtime)
		case rt.Kind != "runtime":
			return invalid("tool %q names %q as its runtime, but that entry is a %s", name, e.Runtime, rt.Kind)
		case rt.Runtime != "":
			// A runtime that needs a runtime would make resolution recursive
			// with no fixed depth; the lock forbids the chain instead.
			return invalid("runtime %q itself names a runtime; runtimes run as themselves", e.Runtime)
		}
	}
	if err := validEntryPath(name, e.Entry); err != nil {
		return err
	}
	// The tool-level digest may be empty when every platform carries its own;
	// what must always hold is that each platform resolves to a confined entry
	// path and a well-formed digest.
	if e.EntrySHA256 != "" && !model.ValidHexID(e.EntrySHA256) {
		return invalid("tool %q entry digest is not a lowercase SHA-256 hex digest", name)
	}
	if len(e.Platforms) == 0 {
		return invalid("tool %q carries no platform payload; a tool available nowhere is a lock mistake", name)
	}
	for _, key := range sortedKeys(e.Platforms) {
		if !supportedPlatforms[key] {
			return invalid("tool %q names platform %q, which is not a supported target", name, key)
		}
		if err := validPayload(name, key, e, e.Platforms[key]); err != nil {
			return err
		}
	}
	return nil
}

func validPayload(name, key string, e Entry, p Payload) error {
	if err := validEntryPath(name, e.entryPath(p)); err != nil {
		return err
	}
	if !model.ValidHexID(e.entryDigest(p)) {
		return invalid("tool %q has no lowercase SHA-256 entry digest for %s", name, key)
	}
	switch p.Provenance {
	case "", "upstream", "built":
	default:
		return invalid("tool %q payload for %s records provenance %q, which is neither upstream nor built", name, key, p.Provenance)
	}
	if !model.ValidHexID(p.SHA256) {
		return invalid("tool %q payload for %s has no lowercase SHA-256 hex digest", name, key)
	}
	if p.Size <= 0 || p.Size > maxPayloadBytes {
		return invalid("tool %q payload for %s declares %d bytes; the bound is 1 to %d", name, key, p.Size, maxPayloadBytes)
	}
	u, err := url.Parse(p.URL)
	if err != nil {
		return invalid("tool %q payload for %s has an unparsable URL", name, key)
	}
	if u.Scheme != "https" || u.Host == "" || u.Path == "" {
		return invalid("tool %q payload for %s is not an absolute https URL with a path", name, key)
	}
	return nil
}

// validToolName bounds what a tool name may be. It becomes a directory name in
// the store and a lock-file name, so it is restricted to characters that need
// no escaping and cannot name a parent, a hidden store directory or a Windows
// reserved device.
func validToolName(name string) error {
	if name == "" || len(name) > 64 {
		return invalid("tool name %q is empty or longer than 64 bytes", name)
	}
	for i := 0; i < len(name); i++ {
		c := name[i]
		ok := (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' || c == '_' || c == '.'
		if !ok {
			return invalid("tool name %q may use only lowercase letters, digits, '-', '_' and '.'", name)
		}
	}
	if strings.HasPrefix(name, ".") {
		return invalid("tool name %q may not start with '.'; the store reserves those names", name)
	}
	return nil
}

// validEntryPath checks the payload-relative executable, script or jar. It must
// be a normalized relative slash path inside the payload, and it may not be the
// publication marker: the marker is written after the payload is renamed into
// place, so a payload that carried one would publish itself.
func validEntryPath(name, entry string) error {
	if entry == "" {
		return invalid("tool %q names no entry executable", name)
	}
	if len(entry) > model.MaxPathBytes {
		return invalid("tool %q entry path is longer than %d bytes", name, model.MaxPathBytes)
	}
	if err := ConfinedRelPath(entry); err != nil {
		return invalid("tool %q entry path %s", name, err)
	}
	if entry == completeName {
		return invalid("tool %q entry may not be the %q publication marker", name, completeName)
	}
	return nil
}

// ConfinedRelPath is the single path rule the product applies to anything that
// comes out of a lock or an archive: a normalized, relative, slash-separated
// path with no NUL, no volume, no "." or ".." component and no trailing slash.
// It is lexical only; the extractor additionally writes through an os.Root, so
// a path that passes here still cannot escape at the syscall level.
//
// It is exported for the same reason ParseLock is: the release-time generator
// in internal/tools/toollock must refuse exactly what the runtime refuses,
// rather than carry a second rule that can drift from this one.
func ConfinedRelPath(p string) error {
	if p == "" {
		return fmt.Errorf("is empty")
	}
	if strings.ContainsRune(p, 0) {
		return fmt.Errorf("contains a NUL byte")
	}
	if strings.ContainsRune(p, '\\') {
		// A backslash is a separator on Windows and an ordinary character
		// elsewhere; a path carrying one means two different things on two
		// platforms, which is not something a pinned payload may do.
		return fmt.Errorf("contains a backslash")
	}
	if strings.HasPrefix(p, "/") {
		return fmt.Errorf("is absolute")
	}
	if len(p) > 1 && p[1] == ':' {
		return fmt.Errorf("carries a volume name")
	}
	if path.Clean(p) != p {
		return fmt.Errorf("is not normalized")
	}
	for _, part := range strings.Split(p, "/") {
		switch part {
		case "":
			return fmt.Errorf("has an empty component")
		case ".":
			return fmt.Errorf("has a %q component", ".")
		case "..":
			return fmt.Errorf("traverses out of the payload")
		}
	}
	return nil
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// toolLanguages is the Section 11.7 matrix read the other way: which languages
// a lock entry unlocks. It is product code keyed by lock entry name, because
// the lock is data and the language table is a product claim about it. A name
// the table does not carry simply reports no languages.
var toolLanguages = map[string][]string{
	"scip-go":                    {"go"},
	"scip-typescript":            {"javascript", "tsx", "typescript"},
	"scip-python":                {"python"},
	"scip-java":                  {"java"},
	"scip-clang":                 {"c", "cpp"},
	"rust-analyzer":              {"rust"},
	"gopls":                      {"go"},
	"typescript-language-server": {"javascript", "tsx", "typescript"},
	"pyright":                    {"python"},
	"clangd":                     {"c", "cpp"},
	"jdtls":                      {"java"},
	"joern":                      {"c", "cpp", "go", "java", "javascript", "python", "rust", "tsx", "typescript"},
}

// EngineLockEntry is the tools.lock.json entry name of the dependence backend,
// and EngineDisplayName is what every shipped string calls it instead.
//
// Section 21 keeps the backend's own project name out of every id, key,
// evidence row, log line, observed version and diagnostic string this product
// emits -- dependence/provider.go already reports it as `engine <version>
// <digest>`. The lock file is generated from the upstream catalogue and must
// keep the real name, so a consumer that renders a lock entry to an operator
// projects it through these two constants rather than carrying a second copy
// of the name.
const (
	EngineLockEntry   = "joern"
	EngineDisplayName = "engine"
)

// DisplayName is the operator-facing name of a lock entry: the entry's own name
// for a managed tool, and the anonymous `engine` for the dependence backend.
func DisplayName(entry string) string {
	if entry == EngineLockEntry {
		return EngineDisplayName
	}
	return entry
}

// languagesOf reports the languages a lock entry unlocks, as a fresh slice so
// no caller can mutate either source. The lock's own list wins: it is generated
// from the same Section 11.7 matrix and keeping two lists where one is
// authoritative is how they drift. The table below is the fallback for a lock
// that does not carry the field.
func languagesOf(name string, e Entry) []string {
	langs := e.Languages
	if len(langs) == 0 {
		langs = toolLanguages[name]
	}
	if len(langs) == 0 {
		return nil
	}
	out := append([]string(nil), langs...)
	sort.Strings(out)
	return out
}
